### ISSUE TITLE
messageEntity以外にもcreatedAtとupdatedAtを追加する。

### ISSUE THREAD

**Issue by TakeshiAono** [TakeshiAono/preliminary-engineere-collaboration#94]

**Comment by cale-i** [comment]
とりあえずテーブル一覧を確認

    tablename    
-----------------
 followers
 chat_rooms
 directories
 files
 members
 messages
 operations
 user_notices
 owners
 project_notices
 projects_users
 roles
 skills
 tasks
 channels
 users
 projects
 offers

**Comment by cale-i** [comment]
進捗管理用

- [ ] followers
- [ ] chat_rooms
- [ ] directories
- [ ] files
- [ ] members
- [ ] messages
- [ ] operations
- [ ] user_notices
- [ ] owners
- [ ] project_notices
- [ ] projects_users
- [ ] roles
- [ ] skills
- [ ] tasks
- [ ] channels
- [ ] users
- [ ] projects
- [ ] offers
